// Generated by https://quicktype.io esta aplicacon para generar interfaces de TypeScript a partir de JSON

// Interface principal que representa los créditos de una película (cast y crew)
export interface Credits {
  id: number; // ID de la película
  cast: Cast[]; // Lista de actores (cast)
  crew: Cast[]; // Lista de miembros del equipo técnico (crew)
}

// Interface que representa a un miembro del reparto o del equipo técnico
export interface Cast {
  adult: boolean; // Indica si es adulto
  gender: number; // Género (1: mujer, 2: hombre, 0 o 3: no especificado)
  id: number; // ID único de la persona
  known_for_department: string; // Departamento por el que es conocido (Acting, Directing, etc.)
  name: string; // Nombre real
  original_name: string; // Nombre original
  popularity: number; // Popularidad
  profile_path: null | string; // Ruta de la imagen de perfil (puede ser null)
  cast_id?: number; // ID de cast (solo para actores)
  character?: string; // Nombre del personaje (solo para actores)
  credit_id: string; // ID del crédito
  order?: number; // Orden de aparición (solo para actores)
  department?: string; // Departamento (solo para crew)
  job?: string; // Trabajo o rol (solo para crew)
}
